CREATE TABLE FILM (
    RENDEZO VARCHAR2(50 CHAR) NOT NULL,
    CIM VARCHAR2(50 CHAR) NOT NULL,
    MEGJELENES DATE NOT NULL,
    IDOTARTAM NUMBER(3) NOT NULL,
    KOLCSONZESI_DIJ NUMBER(3) DEFAULT 135 NOT NULL,
    AZON CHAR(7) NOT NULL,
    ADATHORDOZO VARCHAR2(7 CHAR) NOT NULL,
    MEGJEGYZES LONG,
    FILM_ID NUMBER(10) NOT NULL,
    
    CONSTRAINT FILM_ID_PK PRIMARY KEY (FILM_ID),
    CONSTRAINT AZON_UQ UNIQUE (AZON),
    CONSTRAINT IDOTARTAM_CK CHECK (IDOTARTAM >=15 AND IDOTARTAM <=270),
    CONSTRAINT KOLCSONZESI_DIJ_CK CHECK (KOLCSONZESI_DIJ >=50),
    CONSTRAINT ADATHORDOZO_CK CHECK (ADATHORDOZO IN ('DVD', 'Blu-ray')),
    CONSTRAINT MEGJELENES_CK CHECK (MEGJELENES >= '15-MAR-1848')
);
