CREATE TABLE KOLCSONZES (
    DIJKEDVEZMENY NUMBER(3) DEFAULT 0 NOT NULL,
    ELVITEL_DATUM DATE NOT NULL,
    VISSZAHOZATAL_DATUM DATE,
    FILM_ID NUMBER(10) NOT NULL,
    TAG_ID NUMBER(10) NOT NULL,
    KOLCSONZES_ID NUMBER(10) NOT NULL,
    
    CONSTRAINT DIJKEDVEZMENY_CK CHECK (DIJKEDVEZMENY >= 0 AND DIJKEDVEZMENY <= 100),
    CONSTRAINT VISSZA_DATUM_CK CHECK (VISSZAHOZATAL_DATUM > ELVITEL_DATUM),
    CONSTRAINT FILM_ID_FK FOREIGN KEY (FILM_ID) REFERENCES FILM (FILM_ID),
    CONSTRAINT TAG_ID_FK FOREIGN KEY (TAG_ID) REFERENCES TAGOK (TAG_ID),
    CONSTRAINT KOLCSONZES_ID_PK PRIMARY KEY (KOLCSONZES_ID)
);
