CREATE TABLE TAGOK(
    NEV VARCHAR2(50 CHAR) NOT NULL,
    TAGSAGI_KOD VARCHAR2(10 CHAR) NOT NULL,
    LAKCIM VARCHAR2(50 CHAR)  NOT NULL,
    SZULETESI_DATUM DATE NOT NULL,
    BELEPESI_IDO DATE DEFAULT SYSDATE NOT NULL,
    TAGSAGI_SZINT VARCHAR2(6 CHAR) NOT NULL,
    TAG_ID NUMBER(10) NOT NULL,

    CONSTRAINT TAG_ID_PK PRIMARY KEY (TAG_ID),
    CONSTRAINT TAGSAGI_KOD_UK UNIQUE (TAGSAGI_KOD),
    CONSTRAINT BELEPESI_IDO_CK CHECK (BELEPESI_IDO >= SZULETESI_DATUM),
    CONSTRAINT TAGSAGI_SZINT_CK CHECK (TAGSAGI_SZINT IN ('BASIC', 'SILVER', 'GOLD'))
);
