SELECT
    VIDEO_CODE,
    TITLE,
    RENTAL_DATE,
    RETURN_DATE
FROM
    VIDEOS,
    LOANS
WHERE
    VIDEOS.VIDEO_ID = LOANS.VIDEO_ID
    AND RELEASE_DATE < '01-JAN-2000'
ORDER BY
    RENTAL_DATE DESC, title;