SELECT
    VIDEO_CODE,
    TITLE,
    RENTAL_DATE
FROM
    VIDEOS,
    LOANS
WHERE
    VIDEOS.VIDEO_ID = LOANS.VIDEO_ID
    AND LOANS.RETURN_DATE IS NULL
    AND VIDEOS.TYPE = 'D'
ORDER BY
    RENTAL_DATE DESC, TITLE;